Improve pre-commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,8 +1,13 @@
 # shellcheck disable=SC2148
 
-pre_commit () {
+pre_commit() {
   pnpm exec lint-staged
+  run_tests
+  check_newline
+  check_shellscripts
+}
 
+run_tests() {
   changed_packages=$(git diff --cached --name-only --diff-filter=d | grep -E '\.[jt]sx?$' | cut -d'/' -f2 | sort -u)
   if [ -z "$changed_packages" ]; then
     echo "[pre-commit] Changed packages: none"
@@ -31,6 +36,9 @@ pre_commit () {
     fi
   done
 
+}
+
+check_newline() {
   git diff --cached --name-only --diff-filter=d | while read -r file; do
     if [ -f "$file" ]; then
       # Ensure files have ending newline
@@ -39,12 +47,20 @@ pre_commit () {
         echo "" >> "$file"
       fi
 
-      # Remove trailing whitespace and add back to staging
+      # Remove trailing whitespace
       sed -i 's/\s*$//' "$file"
-      git add "$file"
+
+      # Check for trailing spaces
+      if grep -q "[[:space:]]$" "$file"; then
+        echo "[pre-commit] ❌ Error: Found trailing spaces in $file"
+        echo "[pre-commit] Please remove trailing spaces before committing"
+        exit 1
+      fi
     fi
   done
+}
 
+check_shellscripts() {
   changed_scripts=$(git diff --cached --name-only --diff-filter=d | grep -E '(.husky|\.sh$)' | sort -u)
   if [ -z "$changed_scripts" ]; then
     echo "[pre-commit] Changed scripts: none"
@@ -54,6 +70,7 @@ pre_commit () {
     echo "${changed_scripts[@]}" | xargs shellcheck -x
     echo "[pre-commit] ✅ Shellcheck did end."
   fi
+
 }
 
 show_metrics() {
